services:
  server:
    container_name: server
    build: ./services/server
    ports:
      - 8763:8763
    networks:
      - wet-work
    volumes:
      - type: bind
        source: ./services/server
        target: /usr/local/src/app

  client_one:
    container_name: client_one
    build: ./services/client
    networks:
      - wet-work
    entrypoint: sleep infinity
    volumes:
      - type: bind
        source: ./services/client
        target: /usr/local/src/app

networks:
  wet-work:
    driver: bridge