FROM alpine
    RUN apk update && apk upgrade --available
    RUN apk add --update python3 py3-pip
    COPY ./requirements.txt .
    RUN pip install -r ./requirements.txt
    RUN rm /requirements.txt
